on: push

name: Integration

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-22.04', 'macos-latest', 'windows-latest' ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
            go build -o myproject
            echo ${CGO_ENABLED}
      - name: Run Tests
        shell: bash
        run: |
            go test
            ./myproject & 
            sleep 2
            res= $(curl localhost:3000)
            [[ $res == "Hello, World!" ]] || exit 1
  docker-build:
      runs-on: ubuntu-22.04  
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - name: build
          run: |
            docker build -t goappimage .
        # or
        # - run: echo ABC
